# -*- coding: utf-8 -*-
"""Keyboard_control

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aiw67j_HwAlDR9PFDbwnZ_NMiLGK9Xy2
"""

import keyboard
import time

# Function to handle arrow key presses
def on_key_event(e):
    if e.event_type == keyboard.KEY_DOWN:
        if e.name == 'left':
            # Decrease the width of the claw
            new_width = max(claw1.location - 1, 0)
            claw1.set_loc(new_width)  # Update the width
        elif e.name == 'right':
            # Increase the width of the claw
            new_width = min(claw1.location + 1, claw1.rot_limit)
            claw1.set_loc(new_width)  # Update the width
        elif e.name == 'up':
            # Increase stiffness
            new_stiffness = min(stiffness1.location + 1, stiffness1.rot_limit)
            stiffness1.set_loc(new_stiffness)  # Update the stiffness
        elif e.name == 'down':
            # Decrease stiffness
            new_stiffness = max(stiffness1.location - 1, 0)
            stiffness1.set_loc(new_stiffness)  # Update the stiffness

# Add event listeners for arrow keys
keyboard.on_press(on_key_event)

# Define the limits for claw width and stiffness adjustments
max_width_claw = 100  # Replace this with your actual maximum limit
max_stiffness = 70    # Replace this with your actual maximum limit

# Replace these with your actual instances of claw and stiffness
claw1 = stepper_instance_for_claw1
stiffness1 = stepper_instance_for_stiffness1

# Optionally, you might want to include a loop to keep the script running
# while True:
#     time.sleep(0.1)



#Replace stepper_instance_for_claw1 and stepper_instance_for_stiffness1 with your actual instances of the stepper
#class for controlling the claw and stiffness, respectively. Also, update the max_width_claw and max_stiffness values
#with your desired maximum limits for claw width and stiffness adjustments.

#This code listens for arrow key presses and adjusts the claw width and stiffness within the specified limits